sylius_catalog_backend_category_create:
    pattern: /category/create
    defaults: { _controller: sylius_catalog.controller.backend.category:createAction }
    
sylius_catalog_backend_category_update:
    pattern: /category/{id}/update
    defaults: { _controller: sylius_catalog.controller.backend.category:updateAction }
        
sylius_catalog_backend_category_delete:
    pattern: /category/{id}/delete
    defaults: { _controller: sylius_catalog.controller.backend.category:deleteAction }
    
sylius_catalog_backend_category_list:
    pattern: /categories
    defaults: { _controller: sylius_catalog.controller.backend.category:listAction }
    
sylius_catalog_backend_category_show:
    pattern: /category/{id}
    defaults: { _controller: sylius_catalog.controller.backend.category:showAction }
