sylius_catalog_category_show:
    pattern: /category/{id}/{slug}
    defaults: { _controller: sylius_catalog.controller.frontend.category:showAction }

sylius_catalog_category_list:
    pattern: /categories
    defaults: { _controller: sylius_catalog.controller.frontend.category:listAction }
