sylius_catalog_category_show:
    pattern: /{catalogAlias}/categories/{id}/{slug}
    defaults: { _controller: sylius_catalog.controller.frontend.category:showAction }

sylius_catalog_category_list:
    pattern: /{catalogAlias}/categories/list
    defaults: { _controller: sylius_catalog.controller.frontend.category:listAction }
